"""se crea el modelo nature

Revision ID: d8308119d0dc
Revises: f3fb7fa6d4fb
Create Date: 2024-11-02 19:41:49.189750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8308119d0dc"
down_revision: Union[str, None] = "f3fb7fa6d4fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.Text, nullable=False),
        sa.Column("decreased_stat_id", sa.Integer(), nullable=False),
        sa.Column("increased_stat_id", sa.Integer(), nullable=False),
        sa.Column("hates_flavor_id", sa.Integer(), nullable=False),
        sa.Column("likes_flavor_id", sa.Integer(), nullable=False),
        sa.Column("game_index", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nature")
    # ### end Alembic commands ###
